In [2]:
#import lib
import torch

In [16]:
# make a new tensor
x = torch.empty(5,3) #5 rows, 3 columns
x = torch.rand(5,3) #make random value (0-1): 5 r, 3c
x = torch.randn(5,3)
x = torch.ones(5,3) #value 1
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## Tensor is a multi dimension array, it is used to storage the data and calculate on CPU/GPU
   - ex: scaler(0D): 3: number
   - ex: vector(1D): [1,2,3] :array (x,y,z)
   - ex: matrix(3D): [[1,2],[3,4]] :tabular
   - ex: Tensor(nD): (N,H,C,M,..) data for ML

In [22]:
x = torch.zeros(5,3, dtype = torch.long) #
x = torch.Tensor([5.5, 3.3]) # only 1 rows, divide by 'commas', ex: ([....], [...])
x = torch.Tensor(5,3) # rubbish value with 5 rows and col
x

tensor([[-9.6037e+01,  1.8974e-42,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00]])

In [25]:
y = torch.randn_like(x, dtype = torch.double) # make y tensor size like x (_like),
# with value(randn...) and uses dtype = torch.double..
y

tensor([[ 0.1726,  0.0188,  0.1563],
        [ 0.1388, -1.1742,  0.5619],
        [ 0.3158,  0.4255,  1.6861],
        [ 0.3820, -0.3475, -2.5024],
        [-0.7520,  0.4478, -0.0070]], dtype=torch.float64)

In [28]:
y.shape
y.size()

torch.Size([5, 3])

## Calculation with pytorch

In [33]:
z = x + y #normal 
z = torch.add(x, y) #use method in torch
z

tensor([[-9.5865e+01,  1.8755e-02,  1.1563e+00],
        [ 1.1388e+00, -1.7417e-01,  1.5619e+00],
        [ 1.3158e+00,  1.4255e+00,  2.6861e+00],
        [ 1.3820e+00,  6.5251e-01, -1.5024e+00],
        [ 2.4802e-01,  1.4478e+00,  9.9303e-01]], dtype=torch.float64)

In [36]:
y.add_(x) #make individual and assume later
z = y
z

tensor([[-2.8794e+02,  1.8755e-02,  3.1563e+00],
        [ 3.1388e+00,  1.8258e+00,  3.5619e+00],
        [ 3.3158e+00,  3.4255e+00,  4.6861e+00],
        [ 3.3820e+00,  2.6525e+00,  4.9760e-01],
        [ 2.2480e+00,  3.4478e+00,  2.9930e+00]], dtype=torch.float64)

In [39]:
z = torch.empty(5,3) # make dataframe
torch.add(x,y, out = z) # use special method
z

tensor([[-3.8398e+02,  1.8755e-02,  4.1563e+00],
        [ 4.1388e+00,  2.8258e+00,  4.5619e+00],
        [ 4.3158e+00,  4.4255e+00,  5.6861e+00],
        [ 4.3820e+00,  3.6525e+00,  1.4976e+00],
        [ 3.2480e+00,  4.4478e+00,  3.9930e+00]])

## Index with pytorch

In [45]:
z[ :2, 1:] # take rows from 0 to 1, columns from 1 to 2

#take the center value
z[2,1] # = 4.4255+..

tensor(4.4255)

In [47]:
a = torch.randn(2,4, dtype = torch.double)
a

tensor([[ 1.0784, -0.4525, -0.1085, -0.4944],
        [-0.9116,  0.2266,  0.5074, -0.8161]], dtype=torch.float64)

In [52]:
a.view(8)

tensor([ 1.0784, -0.4525, -0.1085, -0.4944, -0.9116,  0.2266,  0.5074, -0.8161],
       dtype=torch.float64)

In [58]:
b = a.view(-1, 8)
b

tensor([[ 1.0784, -0.4525, -0.1085, -0.4944, -0.9116,  0.2266,  0.5074, -0.8161]],
       dtype=torch.float64)

In [61]:
c = torch.randn(1)
c

tensor([1.3576])

In [62]:
c.item()

1.357573390007019

## Bridge pytorch to numpy
- List value from numpy is easy 

In [63]:
import numpy as np

In [66]:
d = np.ones(3)
d

array([1., 1., 1.])

In [67]:
e = torch.from_numpy(d) # from numpy to pytorch
e


tensor([1., 1., 1.], dtype=torch.float64)

## Move to cal on gpu

In [68]:
device = torch.cuda.is_available()
device

False

In [72]:
if torch.cuda.is_available (): #if compyter have gpu -> do this
    device = torch.device("cuda") # cuda = gpu -> point the tensor runtime
    y = torch.ones_like(x, device = device) # same randn, make code fill with ones, shpe like x
    # run on cuda
    x = x.to(device) # x from cpu, transfer it to cuda to cal
    # want to plus x and y, it is same place as cuda as cpu
    z = x + y
    print(z)

# to the architecture of computer, the calculation on gpu always better with the parralel cal

In [ ]:
#cpu (): move to cal on cpu